import assert from 'node:assert/strict';
import { after, test } from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
const dom = new JSDOM('<div id="root"></div>');
for (const key of ['window','document','HTMLElement','Event','MouseEvent','Node']) globalThis[key] = dom.window[key];
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
window.HTMLDialogElement.prototype.showModal = function() { this.open = true; };
window.HTMLDialogElement.prototype.close = function() { this.open = false; };
const directory = await mkdtemp(resolve('.local', 'draft-review-tests-'));
const output = resolve(directory, 'harness.mjs');
await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import { useState } from 'react';
import { QuestionReviewWorkspace } from './src/features/drafts/QuestionReviewWorkspace';
export function Harness({ saved }) {
  const [draft, setDraft] = useState({id:'preview', status:'draft', content:{}, annotations:[]});
  return <QuestionReviewWorkspace draft={draft} questions={[{prompt:'A'},{prompt:'B'}]} renderQuestion={index => <p data-testid="question">Question {index + 1}</p>} onFinalize={async()=>{}} onSave={async(id,body)=>{saved.push(JSON.parse(body));setDraft(current=>({...current,annotations:[...current.annotations,{id:String(saved.length),body,created_at:String(saved.length)}]}));}} />;
}`},bundle:true,platform:'node',format:'esm',jsx:'automatic',packages:'external',outfile:output});
const { Harness } = await import(pathToFileURL(output));
const { createElement, act } = await import('react');
const { createRoot } = await import('react-dom/client');
const root = createRoot(document.getElementById('root'));
after(async()=>{await act(()=>root.unmount());dom.window.close();await rm(directory,{recursive:true,force:true});});
test('collapsed navigation opens a dialog, jumps and closes; bulk confirmation persists every question',async()=>{
  const saved=[];
  await act(()=>root.render(createElement(Harness,{saved})));
  const dialog=document.querySelector('dialog');
  assert.equal(dialog.open,false);
  await act(()=>document.querySelector('.question-review-navigation-trigger').click());
  assert.equal(dialog.open,true);
  await act(()=>dialog.querySelectorAll('.question-review-number-grid button')[1].click());
  assert.equal(dialog.open,false);
  assert.equal(document.querySelector('[data-testid="question"]').textContent,'Question 2');
  await act(async()=>document.querySelector('.question-review-confirm-all').click());
  assert.deepEqual(saved.map(entry=>[entry.number,entry.confirmed]),[[1,true],[2,true]]);
  assert.equal(document.querySelector('.question-review-confirm-all').textContent,'全部已确认');
  assert.equal(document.querySelector('.question-review-confirm').disabled,false);
});
