import assert from 'node:assert/strict';
import { test, afterEach, after } from 'node:test';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
const dom = new JSDOM('<!doctype html><div id="root"></div>', { url: 'http://localhost', pretendToBeVisual: true });
for (const key of ['window','document','HTMLElement','Event','Node']) globalThis[key] = dom.window[key];
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
await mkdir('.local', {recursive:true});
const dir = await mkdtemp(resolve('.local','no-character-'));
const out = resolve(dir,'fixture.mjs');
await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`export { PracticePanel } from './src/features/practice/StudyPanels'; export { translations } from './src/i18n/translations';`},bundle:true,platform:'node',format:'esm',jsx:'automatic',packages:'external',loader:{'.css':'empty'},outfile:out});
const {PracticePanel,translations}=await import(pathToFileURL(out));
const {act,createElement:h}=await import('react');
const {createRoot}=await import('react-dom/client');
let root;
afterEach(async()=>{await act(async()=>root?.unmount());});
after(async()=>{dom.window.close();await rm(dir,{recursive:true,force:true});});
test('accepted answers retain feedback without a character or animation', async () => {
  const q = { id: 'q1', itemId: 'word1', kind: 'grammar', title: 'Question', prompt: '問題', choices: ['甲', '乙'], answer: '乙' };
  const noop = () => {};
  const props = { activeQuestion: q, questions: [q], questionsLength: 1, activeIndex: 0, answeredCount: 0, complete: false, feedbackMode: 'immediate', answers: {}, items: [], labels: translations['zh-CN'], questionTypeLabel: 'Test', settings: { locale: 'zh-CN', showExplanationRuby: false }, onAnswer: noop, onPrev: noop, onNext: noop, onJump: noop, onRestart: noop, onPracticeHome: noop, onPrepareReview: async () => {}, onReview: noop, analysisStatus: 'idle' };
  root = createRoot(document.getElementById('root'));
  await act(async () => root.render(h(PracticePanel, props)));
  await act(async () => document.querySelectorAll('.practice-answer-choices button')[1].click());
  assert.equal(document.querySelector('[data-mascot-action]'), null);
  await act(async () => root.render(h(PracticePanel, { ...props, answers: { q1: { selected: '乙', correct: true } }, answeredCount: 1 })));
  assert.equal(document.querySelector('[data-mascot-action]'), null);
  assert.equal(document.querySelector('img[src*="companion"]'), null);
});
