// 題庫画面の表示文字（UI 言語ごと）。
import type { Locale } from '../../types';
import type { GroupStatus, QuestionModule } from '../../v3/types';

const zh = {
  title: { vocabulary: '词汇题库', grammar: '语法题库', reading: '阅读题库', listening: '听力题库' } as Record<QuestionModule, string>,
  search: '搜索题干、选项或编号', allTypes: '全部题型', allStatuses: '全部状态', allLevels: '全部等级', total: (n: number) => `共 ${n} 组`, empty: '没有符合条件的题目',
  loading: '读取中…', loadError: '读取失败', create: '新建题目', back: '返回列表', previous: '上一页', next: '下一页',
  status: { draft: '草稿', needs_review: '待审查', needs_revision: '需修改', ready: '可用', retired: '已停用' } as Record<GroupStatus, string>,
  instruction: '作答说明', context: '场景说明', materials: '素材', questions: '小题', options: '选项', correct: '正确答案', explanation: '解析', evidence: '依据',
  knowledge: '相关知识点', tags: '标签', expectedText: '参考答案', review: '审查', latestReview: '最近审查', openFindings: '待处理的问题', noReview: '还没有审查记录',
  section: { basis: '正确依据', step: '解题步骤', full_answer: '完整答案', tip: '技巧', objective: '学习目标' } as Record<string, string>,
  role: { main: '文章', passage_a: '文章 A', passage_b: '文章 B', notice: '公告・表格', scene_image: '场景图', audio: '音频' } as Record<string, string>,
  edit: '编辑', retire: '停用', restore: '恢复待审查', remove: '删除', confirmRemove: (code: string) => `删除题组 ${code}？已被练习使用的题目不能删除。`,
  reviewHint: '题目创建或修改后由 AI 审查，通过后才会用于练习。', verdict: { pass: '通过', revise: '需修改', reject: '不可用' } as Record<string, string>,
  reviewer: { system: '自动检查', ai: 'AI', user: '学习者' } as Record<string, string>,
  // 编辑
  newTitle: '新建题目', editTitle: (code: string) => `编辑 ${code}`, type: '题型', level: '等级', none: '未指定', save: '保存', saving: '保存中…', cancel: '取消', saveDraft: '存为草稿',
  prompt: '题干', translation: '译文', target: '考查部分（在题干中的文字）', markFound: (text: string) => `已标记：${text}`, markMissing: '题干中找不到这段文字',
  blankAuto: '题干中的（　）自动作为空位', starAuto: '题干中的（　）为空位、（★）为★空位，自动识别', passageBlankAuto: (n: number) => `对应文章中的空位（${n}）`,
  option: (n: number) => `选项 ${n}`, optionText: '选项文字', analysis: '为什么对或错', distractorType: '干扰类型', addOption: '添加选项', removeOption: '删除',
  spokenOptions: '这类题的选项在音频里读出，可以只保留编号。',
  addSection: '添加段落', sectionKind: '段落类型', sectionBody: '内容', addQuestion: '添加小题', removeQuestion: '删除小题', question: (n: number) => `第 ${n} 题`,
  body: '正文（日语）', transcript: '听力原文（日语）', file: '文件', upload: '上传', uploaded: (id: number) => `已上传：文件 ${id}`, uploading: '上传中…',
  knowledgeCodes: '知识点编号（如 W12, G3，用逗号分隔）', tagsInput: '标签（逗号分隔）', sourceReference: '出处',
  errors: '需要修改', warnings: '提醒（不影响保存，会交给审查）', valid: '符合题型规则', serverErrors: '服务器拒绝保存：',
  rulesOf: (label: string) => `${label} 的要求`, required: '必填', forbidden: '不需要',
};
type Text = typeof zh;
const ja: Text = {
  ...zh,
  title: { vocabulary: '語彙の問題', grammar: '文法の問題', reading: '読解の問題', listening: '聴解の問題' }, search: '問題文・選択肢・番号で検索', allTypes: 'すべての問題形式',
  allStatuses: 'すべての状態', allLevels: 'すべてのレベル', total: (n) => `${n} 組`, empty: '条件に合う問題はありません', loading: '読み込み中…', loadError: '読み込みに失敗しました',
  create: '問題を作る', back: '一覧に戻る', previous: '前へ', next: '次へ',
  status: { draft: '下書き', needs_review: '審査待ち', needs_revision: '要修正', ready: '使用可', retired: '停止中' },
  instruction: '指示文', context: '場面の説明', materials: '素材', questions: '小問', options: '選択肢', correct: '正解', explanation: '解説', evidence: '根拠',
  knowledge: '関連する項目', tags: 'タグ', expectedText: '模範解答', review: '審査', latestReview: '最新の審査', openFindings: '未対応の指摘', noReview: '審査の記録はまだありません',
  section: { basis: '正解の根拠', step: '解き方', full_answer: '完成文', tip: 'コツ', objective: '学習目標' },
  role: { main: '本文', passage_a: '本文 A', passage_b: '本文 B', notice: 'お知らせ・表', scene_image: '場面の絵', audio: '音声' },
  edit: '編集', retire: '停止', restore: '審査待ちに戻す', remove: '削除', confirmRemove: (code) => `問題 ${code} を削除しますか？練習で使われた問題は削除できません。`,
  reviewHint: '作成・修正した問題は AI が審査し、通ったものだけが練習に使われます。', verdict: { pass: '合格', revise: '要修正', reject: '不可' },
  reviewer: { system: '自動チェック', ai: 'AI', user: '学習者' },
  newTitle: '問題を作る', editTitle: (code) => `${code} を編集`, type: '問題形式', level: 'レベル', none: '指定なし', save: '保存', saving: '保存中…', cancel: 'キャンセル', saveDraft: '下書きとして保存',
  prompt: '問題文', translation: '訳', target: '問われている部分（問題文中の文字）', markFound: (text) => `マーク済み：${text}`, markMissing: '問題文にこの文字が見つかりません',
  blankAuto: '問題文の（　）を空欄として自動で認識します', starAuto: '問題文の（　）を空欄、（★）を★の空欄として自動で認識します', passageBlankAuto: (n) => `本文の空欄（${n}）に対応`,
  option: (n) => `選択肢 ${n}`, optionText: '選択肢の文字', analysis: '正しい・誤りの理由', distractorType: '誤答の種類', addOption: '選択肢を追加', removeOption: '削除',
  spokenOptions: 'この形式の選択肢は音声の中で読み上げられるので、番号だけでかまいません。',
  addSection: '段落を追加', sectionKind: '段落の種類', sectionBody: '内容', addQuestion: '小問を追加', removeQuestion: '小問を削除', question: (n) => `問 ${n}`,
  body: '本文（日本語）', transcript: 'スクリプト（日本語）', file: 'ファイル', upload: 'アップロード', uploaded: (id) => `アップロード済み：ファイル ${id}`, uploading: 'アップロード中…',
  knowledgeCodes: '項目の番号（W12, G3 など。カンマ区切り）', tagsInput: 'タグ（カンマ区切り）', sourceReference: '出典',
  errors: '修正が必要', warnings: '注意（保存はでき、審査に回ります）', valid: '問題形式の規則を満たしています', serverErrors: 'サーバーが保存を拒否しました：',
  rulesOf: (label) => `${label} の条件`, required: '必須', forbidden: '不要',
};
const en: Text = {
  ...zh,
  title: { vocabulary: 'Vocabulary questions', grammar: 'Grammar questions', reading: 'Reading questions', listening: 'Listening questions' }, search: 'Search prompt, options or code',
  allTypes: 'All types', allStatuses: 'All states', allLevels: 'All levels', total: (n) => `${n} groups`, empty: 'No questions match these filters', loading: 'Loading…', loadError: 'Could not load',
  create: 'New question', back: 'Back to list', previous: 'Previous', next: 'Next',
  status: { draft: 'Draft', needs_review: 'Waiting for review', needs_revision: 'Needs revision', ready: 'Ready', retired: 'Retired' },
  instruction: 'Instructions', context: 'Scene', materials: 'Materials', questions: 'Questions', options: 'Options', correct: 'Answer', explanation: 'Explanation', evidence: 'Evidence',
  knowledge: 'Related items', tags: 'Tags', expectedText: 'Reference answer', review: 'Review', latestReview: 'Latest review', openFindings: 'Open findings', noReview: 'Not reviewed yet',
  section: { basis: 'Why this answer', step: 'Steps', full_answer: 'Full answer', tip: 'Tip', objective: 'Objective' },
  role: { main: 'Passage', passage_a: 'Passage A', passage_b: 'Passage B', notice: 'Notice / table', scene_image: 'Scene image', audio: 'Audio' },
  edit: 'Edit', retire: 'Retire', restore: 'Send back to review', remove: 'Delete', confirmRemove: (code) => `Delete question group ${code}? Questions used in practice cannot be deleted.`,
  reviewHint: 'New and edited questions are reviewed by AI and used in practice only after they pass.', verdict: { pass: 'Pass', revise: 'Revise', reject: 'Reject' },
  reviewer: { system: 'Automatic check', ai: 'AI', user: 'Learner' },
  newTitle: 'New question', editTitle: (code) => `Edit ${code}`, type: 'Type', level: 'Level', none: 'Not set', save: 'Save', saving: 'Saving…', cancel: 'Cancel', saveDraft: 'Save as draft',
  prompt: 'Prompt', translation: 'Translation', target: 'Tested part (text in the prompt)', markFound: (text) => `Marked: ${text}`, markMissing: 'This text is not in the prompt',
  blankAuto: 'The （　） in the prompt is used as the blank', starAuto: '（　） in the prompt are blanks and （★） is the ★ blank, detected automatically', passageBlankAuto: (n) => `Blank (${n}) in the passage`,
  option: (n) => `Option ${n}`, optionText: 'Option text', analysis: 'Why it is right or wrong', distractorType: 'Distractor type', addOption: 'Add option', removeOption: 'Remove',
  spokenOptions: 'Options of this type are read out in the audio; numbers alone are fine.',
  addSection: 'Add section', sectionKind: 'Section type', sectionBody: 'Content', addQuestion: 'Add question', removeQuestion: 'Remove question', question: (n) => `Question ${n}`,
  body: 'Text (Japanese)', transcript: 'Transcript (Japanese)', file: 'File', upload: 'Upload', uploaded: (id) => `Uploaded: file ${id}`, uploading: 'Uploading…',
  knowledgeCodes: 'Item codes (W12, G3, comma separated)', tagsInput: 'Tags (comma separated)', sourceReference: 'Source',
  errors: 'Needs changes', warnings: 'Warnings (saving is allowed; they go to review)', valid: 'Meets the rules of this type', serverErrors: 'The server refused to save:',
  rulesOf: (label) => `Requirements of ${label}`, required: 'Required', forbidden: 'Not used',
};
export const bankText = (locale: Locale): Text => (locale === 'ja' ? ja : locale === 'en' ? en : zh);
