import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const dir = mkdtempSync(join(tmpdir(), 'jlpt-exam-goal-'));
process.env.JLPT_DB_PATH = join(dir, 'test.sqlite');
process.env.JLPT_REVIEW_DATA_PATH = join(dir, 'data');
mkdirSync(process.env.JLPT_REVIEW_DATA_PATH);
const { createUser, getStudyPlan, saveStudyPlanProfile, saveGeneratedStudyPlan, getDb } = await import('./storage.mjs');
after(() => { getDb().close(); rmSync(dir, { recursive: true, force: true }); });
test('exam goals persist date-only, JLPT and custom choices without replacing tasks or materials', () => {
  const user = createUser('exam-target', 'test-password');
  const original = getStudyPlan(user.id);
  assert.equal(original.profile.level, '');
  const profile = { ...original.profile, startDate: '2026-10-05', examDate: '2026-12-06' };
  const first = saveStudyPlanProfile(user.id, { ...profile, examName: 'JLPT', level: 'N2' });
  assert.equal(first.profile.level, 'N2');
  saveGeneratedStudyPlan(user.id, { tasks: [{ id: 'task-one', date: '2026-10-06', title: '复习', module: 'grammar', minutes: 30 }] });
  const before = getStudyPlan(user.id);
  const custom = saveStudyPlanProfile(user.id, { ...before.profile, examName: 'TOEIC', level: 'N2', examDate: '2026-12-20' });
  assert.equal(custom.profile.examName, 'TOEIC');
  assert.equal(custom.profile.level, '');
  assert.equal(custom.profile.examDate, '2026-12-20');
  assert.deepEqual(custom.tasks, before.tasks);
  assert.deepEqual(custom.profile.materials, before.profile.materials);
  const dateOnly = saveStudyPlanProfile(user.id, { ...custom.profile, examName: '', level: '' });
  assert.equal(dateOnly.profile.level, '');
  assert.equal(dateOnly.profile.examName, '');
  assert.equal(getStudyPlan(user.id).profile.examDate, '2026-12-20');
});
