import {test,after} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const dir=mkdtempSync(join(tmpdir(),'jlpt-typed-session-'));process.env.JLPT_DB_PATH=join(dir,'test.sqlite');process.env.JLPT_REVIEW_DATA_PATH=join(dir,'data');mkdirSync(process.env.JLPT_REVIEW_DATA_PATH);
const storage=await import('./storage.mjs');const {attachPracticeReferences}=await import('./bank-materials.mjs');const {tools}=await import('./mcp-tools.mjs');
const owner=storage.createUser('typed-owner','password-one'),db=storage.getDb();after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
test('MCP grades the frozen star, preserves full order and withholds unrevealed canonical answers',async()=>{
 const q={id:'typed-assembly',itemId:'IT-typed',kind:'grammar',questionTypeId:'grammar-composition',prompt:'彼は ＿＿ ＿＿ ★ ＿＿ です。',choices:['昨日','駅で','会った','人'],answer:'会った',assembly:{starSlot:2,correctOrder:['option-0','option-1','option-2','option-3']},correctReason:'★は会った。'};
 const practice=attachPracticeReferences(db,owner.id,{id:'typed-practice',questions:[q,{...q,id:'typed-assembly2'}]});
 db.prepare("INSERT INTO daily_practices(id,user_id,practice_date,version,title,minutes,practice_json,created_at,updated_at) VALUES(?,?,'2026-10-07',1,'Typed',10,?,'2026-10-07','2026-10-07')").run(practice.id,owner.id,JSON.stringify(practice));
 const before=storage.getPracticeSession(owner.id,practice.id);assert.equal(before.questions[0].presentation.payload.answer,undefined);assert.equal(before.questions[0].presentation.payload.legacy.assembly.correctOrder,undefined);
 const tool=tools.find(t=>t.name==='submit_practice_answer');
 await assert.rejects(tool.handler({practice_id:practice.id,question_id:q.id,selected:'会った',assemblyOrder:['option-2']},{ownerId:String(owner.id)}),/Complete assembly/);
 assert.equal(storage.getStudyState(owner.id).attemptHistory.length,0);
 const order=['option-0','option-1','option-2','option-3'];const response=await tool.handler({practice_id:practice.id,question_id:q.id,selected:'会った',assemblyOrder:order},{ownerId:String(owner.id)});
 assert.equal(response.structuredContent.question.correct,true);assert.deepEqual(response.structuredContent.question.assemblyOrder,order);
 const history=storage.getStudyState(owner.id).attemptHistory[0];assert.deepEqual(history.answers[0].assemblyOrder,order);assert.equal(history.questionManifest[0].snapshot.presentation.payload.answer.optionId,'option-2');
 assert.equal(response.structuredContent.next.presentation.payload.answer,undefined);
 const changed={...practice,questions:practice.questions.map(q=>({...q,prompt:'改訂後',answer:'昨日'}))};db.prepare('UPDATE daily_practices SET practice_json=? WHERE id=?').run(JSON.stringify(changed),practice.id);
 const frozen=storage.getPracticeSession(owner.id,practice.id);assert.equal(frozen.questions[0].prompt,q.prompt);assert.equal(frozen.questions[0].answer,'会った');assert.deepEqual(frozen.questions[0].assemblyOrder,order);
});
