import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const dir = mkdtempSync(join(tmpdir(), 'jlpt-word-lookup-'));
process.env.JLPT_DB_PATH = join(dir, 'test.sqlite');
process.env.JLPT_REVIEW_DATA_PATH = join(dir, 'data');
mkdirSync(process.env.JLPT_REVIEW_DATA_PATH);
const storage = await import('./storage.mjs');
const { tools } = await import('./mcp-tools.mjs');
const { createApiHandler } = await import('./api-handler.mjs');
after(() => { storage.getDb().close(); rmSync(dir, { recursive: true, force: true }); });
test('word lookup capture POST retains context and is readable by the owner through MCP', async () => {
  const user = storage.createUser('lookup-test', 'password-one');
  const other = storage.createUser('lookup-other', 'password-two');
  const { token } = storage.loginUser('lookup-test', 'password-one');
  const input = { body: 'コーナー', category: 'word', targetDeck: 'n1_vocab', context: '记忆卡点词查询\n原文：輪投げのコーナーに人が並んでいる。' };
  let status, body;
  await createApiHandler({})({ method: 'POST', url: '/api/captures', headers: { host: 'localhost', authorization: `Bearer ${token}` }, async *[Symbol.asyncIterator]() { yield Buffer.from(JSON.stringify(input)); } }, { writeHead(code) { status = code; }, end(value) { body = JSON.parse(value); } });
  assert.equal(status, 201);
  const list = tools.find((tool) => tool.name === 'list_learning_captures');
  const read = async (owner) => { const result = await list.handler({ status: 'inbox' }, { ownerId: String(owner.id) }); return result.structuredContent ?? JSON.parse(result.content[0].text); };
  const captures = await read(user);
  assert.ok(JSON.stringify(captures).includes(body.capture.id));
  assert.ok(JSON.stringify(captures).includes(input.body));
  assert.equal(storage.listLearningCaptures(user.id, 'inbox')[0].context, input.context);
  assert.ok(!JSON.stringify(await read(other)).includes(body.capture.id));
});
