import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';import {buildCloudApi} from '../scripts/build-cloud-api.mjs';import {digest,auditTestCopy} from '../server/cloud-copy.mjs';
test('real DO export mode skips constructor migrations, normal dispatch, R2 delete queue and alarms',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'jlpt-copy-do-')),scriptPath='.local/cloud-api-build/test-copy-runtime.mjs';await buildCloudApi('cloudflare/fixtures/copy-export.mjs',scriptPath);
 const token='fixture-only-export-token-123456789';const options=convertV4MiniflareOptions({modules:true,scriptPath,compatibilityDate:'2026-09-20',compatibilityFlags:['nodejs_compat'],durableObjects:{JLPT_DATABASE:{className:'JlptDatabase',useSQLite:true}},r2Buckets:['MEDIA'],bindings:{COPY_EXPORT_MODE:'read-only',COPY_EXPORT_TOKEN:token,COPY_EXPORT_OWNERS:'[1]'},durableObjectsPersist:join(dir,'db'),r2Persist:join(dir,'r2')});options.resourcePersistencePath=join(dir,'state');let mf=new Miniflare(options);
 const request=(path,method='GET',body,credential=token)=>mf.dispatchFetch('http://localhost'+path,{method,headers:{authorization:'Bearer '+credential},...(body?{body:JSON.stringify(body)}:{})});
 try{const initial=await(await request('/__fixture/inspect')).json();assert.deepEqual(initial,{tables:[],deletes:null,alarm:null});assert.equal((await request('/__fixture/seed')).status,200);const before=await(await request('/__fixture/inspect')).json();assert.equal((await request('/api/health')).status,404);assert.equal((await request('/__test-copy/snapshot','POST',{owners:[1]},'live-session')).status,403);assert.equal((await request('/__test-copy/snapshot','POST',{owners:[2]})).status,403);
  const response=await request('/__test-copy/snapshot','POST',{owners:[1]});assert.equal(response.status,200,await response.clone().text());const manifest=await response.json(),buffers=[];for(const c of manifest.chunks){const result=await request(`/__test-copy/snapshots/${manifest.snapshotId}/chunks/${c.index}`),data=new Uint8Array(await result.arrayBuffer());assert.equal(digest(data),c.sha256);buffers.push(Buffer.from(data));}const bytes=Buffer.concat(buffers);assert.equal(digest(bytes),manifest.snapshotId);const snapshot=JSON.parse(bytes.toString());assert.equal(auditTestCopy(snapshot).valid,true);assert.equal(snapshot.tables.progress.rows.length,1);assert.equal(bytes.toString().includes('password-secret'),false);assert.equal(bytes.toString().includes('other-owner'),false);
  await request('/__fixture/alarm');assert.deepEqual(await(await request('/__fixture/inspect')).json(),before);const bucket=await mf.getR2Bucket('MEDIA');assert.equal(await(await bucket.get('item-images/keep-me')).text(),'fixture');
  await mf.dispose();mf=new Miniflare(options);assert.equal((await request(`/__test-copy/snapshots/${manifest.snapshotId}/chunks/0`)).status,404,'restart invalidates volatile snapshot rather than mixing current rows');assert.deepEqual(await(await request('/__fixture/inspect')).json(),before);
 }finally{await mf.dispose();rmSync(dir,{recursive:true,force:true});}
});
