// 从 server/v3/schema.sql 生成设计文档的“全部表字段”附录（中文、英文、日文三份文档中两个标记之间的内容会被替换）。
// 列的含义取自 SQL 注释；“取值 / 示例”“旧数据来源”取自 server/v3/column-notes.json；
// 英文、日文版的内容性文字查 server/v3/schema-doc.i18n.json（中文原文 → en / ja）。
// 用法：node scripts/v3/schema-doc.mjs            生成并写回三份文档
//       node scripts/v3/schema-doc.mjs --check    只检查文档是否与 SQL 一致、翻译是否齐全（不一致时退出码 1）
//       node scripts/v3/schema-doc.mjs --missing  列出缺少翻译的中文原文（JSON）
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const root = new URL('../../', import.meta.url);
const sql = readFileSync(new URL('server/v3/schema.sql', root), 'utf8');
const notes = JSON.parse(readFileSync(new URL('server/v3/column-notes.json', root), 'utf8'));
const i18nUrl = new URL('server/v3/schema-doc.i18n.json', root);
const dictionary = existsSync(i18nUrl) ? JSON.parse(readFileSync(i18nUrl, 'utf8')) : {};
const END = '<!-- schema-doc:end -->';

const LOCALES = {
  zh: {
    doc: 'docs/schema-v3-design.md',
    begin: '<!-- schema-doc:begin（以下由 scripts/v3/schema-doc.mjs 从 server/v3/schema.sql 生成，请勿手改） -->',
    title: '## 附录：全部表字段',
    intro: '每张表的全部列，含内部主键、所属用户、时间列与外键。“必填”为空表示可以为空；“约束 / 引用”中的 → 表示外键。“译文字段”不是表的列，存在 `content_translations`（见 §3）。',
    view: '（视图）',
    viewHeader: '| 列 | 含义 |',
    header: '| 列 | 类型 | 必填 | 默认 | 约束 / 引用 | 含义 | 取值 / 示例 | 旧数据来源 |',
    yes: '是',
    primaryKey: '主键',
    cascade: '，随之删除', setNull: '，删除后置空', restrict: '，被引用时不能删除',
    values: '取值：', range: '范围', separator: '；', listSeparator: '、',
    constraints: '表级约束：', index: '索引', uniqueIndex: '唯一索引', colon: '：',
    translations: (table) => `译文字段（\`content_translations.owner_table\` = \`${table}\`）：`,
    includesJa: '（含 ja）',
    common: { rid: '内部主键（整数自增）', user_id: '所属用户', created_at: '创建时间', updated_at: '最后修改时间', position: '在列表中的顺序，从 0 开始' },
    commonSource: { rid: '新生成', user_id: '旧表的 `user_id`', created_at: '旧表的 `created_at`；旧数据没有时取迁移时间', updated_at: '旧表的 `updated_at`；旧数据没有时取迁移时间', position: '旧数组中的顺序', code: '新生成' },
  },
  en: {
    doc: 'docs/schema-v3-design.en.md',
    begin: '<!-- schema-doc:begin (generated by scripts/v3/schema-doc.mjs from server/v3/schema.sql; do not edit by hand) -->',
    title: '## Appendix: All Table Columns',
    intro: 'Every column of every table, including internal keys, owner, timestamps and foreign keys. An empty "Required" cell means the column may be null; → in "Constraint / reference" marks a foreign key. "Translated fields" are not table columns; they are stored in `content_translations` (see §3).',
    view: ' (view)',
    viewHeader: '| Column | Meaning |',
    header: '| Column | Type | Required | Default | Constraint / reference | Meaning | Values / example | Legacy source |',
    yes: 'yes',
    primaryKey: 'primary key',
    cascade: ', deleted with it', setNull: ', set to null on delete', restrict: ', cannot be deleted while referenced',
    values: 'values: ', range: 'range', separator: '; ', listSeparator: ', ',
    constraints: 'Table constraints: ', index: 'Index', uniqueIndex: 'Unique index', colon: ': ',
    translations: (table) => `Translated fields (\`content_translations.owner_table\` = \`${table}\`): `,
    includesJa: ' (includes ja)',
    common: { rid: 'Internal primary key (auto-increment integer)', user_id: 'Owning user', created_at: 'Creation time', updated_at: 'Last modification time', position: 'Order within the list, starting at 0' },
    commonSource: { rid: 'Generated', user_id: '`user_id` of the legacy table', created_at: '`created_at` of the legacy table; migration time when missing', updated_at: '`updated_at` of the legacy table; migration time when missing', position: 'Order in the legacy array', code: 'Generated' },
  },
  ja: {
    doc: 'docs/schema-v3-design.ja.md',
    begin: '<!-- schema-doc:begin（以下は scripts/v3/schema-doc.mjs が server/v3/schema.sql から生成。手で編集しないこと） -->',
    title: '## 付録：全テーブルの列',
    intro: '全テーブルの全列（内部主キー、所有ユーザー、日時列、外部キーを含む）。「必須」が空欄の列は NULL を許容します。「制約 / 参照」の → は外部キーです。「翻訳フィールド」はテーブルの列ではなく、`content_translations` に保存されます（§3 参照）。',
    view: '（ビュー）',
    viewHeader: '| 列 | 意味 |',
    header: '| 列 | 型 | 必須 | 既定値 | 制約 / 参照 | 意味 | 値 / 例 | 旧データの出所 |',
    yes: '必須',
    primaryKey: '主キー',
    cascade: '、連動して削除', setNull: '、削除時に NULL', restrict: '、参照中は削除不可',
    values: '値：', range: '範囲', separator: '；', listSeparator: '、',
    constraints: 'テーブル制約：', index: 'インデックス', uniqueIndex: '一意インデックス', colon: '：',
    translations: (table) => `翻訳フィールド（\`content_translations.owner_table\` = \`${table}\`）：`,
    includesJa: '（ja を含む）',
    common: { rid: '内部主キー（自動採番の整数）', user_id: '所有ユーザー', created_at: '作成日時', updated_at: '最終更新日時', position: 'リスト内の順序（0 始まり）' },
    commonSource: { rid: '新規生成', user_id: '旧テーブルの `user_id`', created_at: '旧テーブルの `created_at`。旧データにない場合は移行日時', updated_at: '旧テーブルの `updated_at`。旧データにない場合は移行日時', position: '旧配列内の順序', code: '新規生成' },
  },
};

const escape = (text) => String(text ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const hasChinese = (text) => /[\u4e00-\u9fff\u3000-\u303f\uff08\uff09\uff1a\uff1b\uff0c]/.test(text ?? '');

/** 解析 CREATE TABLE / CREATE VIEW / CREATE INDEX，以及每张表前的注释和分节标题。 */
function parse(source) {
  const lines = source.split('\n');
  const sections = [];
  const translations = new Map();
  for (const m of source.matchAll(/\('([a-z_]+)', '([a-z_]+)', '([^']*)', (\d), (\d)\)/g)) {
    if (!translations.has(m[1])) translations.set(m[1], []);
    translations.get(m[1]).push({ field: m[2], description: m[3], allowsJa: m[4] === '1' });
  }
  let section = null;
  let pendingComment = [];
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    const title = /^-- (\d+[a-z]?)\. (.+)$/.exec(line);
    if (title && lines[i - 1]?.startsWith('-- ====')) {
      section = { number: title[1], title: title[2], tables: [] };
      sections.push(section);
      pendingComment = [];
      continue;
    }
    if (line.startsWith('-- ====')) continue;
    if (/^-- /.test(line) && !/^-- 译文字段/.test(line)) { pendingComment.push(line.slice(3)); continue; }
    const create = /^CREATE TABLE (\w+) \($/.exec(line);
    if (create) {
      const table = { name: create[1], comment: pendingComment.join(' '), columns: [], constraints: [], indexes: [] };
      pendingComment = [];
      for (i += 1; !/^\);/.test(lines[i]); i += 1) {
        const body = lines[i];
        const column = /^\s{2}(\w+)\s+(INTEGER|TEXT|REAL)\b(.*?)(?:\s+--\s*(.*))?$/.exec(body);
        if (column && !['PRIMARY', 'UNIQUE', 'FOREIGN', 'CHECK'].includes(column[1])) {
          table.columns.push({ name: column[1], type: column[2], definition: column[3].trim().replace(/,$/, ''), comment: column[4] ?? '' });
          continue;
        }
        const continuation = /^\s+--\s*(.*)$/.exec(body);
        if (continuation && table.columns.length) {
          const last = table.columns.at(-1);
          last.comment = [last.comment, continuation[1]].filter(Boolean).join(' ');
          continue;
        }
        const extra = /^\s{2,}(\S.*?)(?:\s+--.*)?$/.exec(body);
        if (!extra) continue;
        const text = extra[1].replace(/,$/, '');
        if (/^(PRIMARY KEY|UNIQUE|FOREIGN KEY|CHECK)/.test(text)) table.constraints.push(text);
        else if (table.columns.length) table.columns.at(-1).definition += ` ${text}`;
      }
      table.translations = translations.get(table.name) ?? [];
      section.tables.push(table);
      continue;
    }
    const index = /^CREATE (UNIQUE )?INDEX (\w+) ON (\w+) \((.+?)\)(.*);$/.exec(line);
    if (index) {
      const table = sections.flatMap((s) => s.tables).find((t) => t.name === index[3]);
      table?.indexes.push({ unique: Boolean(index[1]), name: index[2], columns: index[4], where: index[5].trim() });
      continue;
    }
    if (/^CREATE VIEW (\w+)/.test(line)) {
      const name = /^CREATE VIEW (\w+)/.exec(line)[1];
      const view = { name, comment: pendingComment.join(' '), view: true, columns: [] };
      pendingComment = [];
      for (i += 1; !/;$/.test(lines[i - 1] ?? '') || i === 0; i += 1) {
        const column = /AS (\w+),?\s*(?:--\s*(.*))?$/.exec(lines[i]);
        if (column && !/^FROM|JOIN|GROUP/.test(lines[i].trim())) view.columns.push({ name: column[1], comment: column[2] ?? '' });
        if (/;$/.test(lines[i])) break;
      }
      section.tables.push(view);
      continue;
    }
    if (line.trim() === '' || /^-- 译文字段/.test(line)) pendingComment = /^-- 译文字段/.test(line) ? pendingComment : [];
  }
  return sections;
}

function render(sections, lang, missing) {
  const L = LOCALES[lang];
  // 内容性文字：中文原样；其他语言查对照表，缺失时记下并暂用中文
  const t = (text) => {
    if (!text || lang === 'zh' || !hasChinese(text)) return text;
    const hit = dictionary[text]?.[lang];
    if (hit) return hit;
    missing.add(text);
    return text;
  };
  const describe = (column) => {
    const def = column.definition;
    const reference = /REFERENCES (\w+)\((\w+)\)(?: ON DELETE (CASCADE|SET NULL))?/.exec(def);
    const check = /CHECK \((\w+) IN \(([^)]*)\)\)/.exec(def);
    const between = /CHECK \((\w+) BETWEEN (\S+) AND (\S+)\)/.exec(def);
    const defaultValue = /DEFAULT ('[^']*'|\S+)/.exec(def)?.[1];
    const rules = [];
    if (/PRIMARY KEY/.test(def)) rules.push(L.primaryKey);
    if (reference) rules.push(`→ \`${reference[1]}.${reference[2]}\`${reference[3] === 'CASCADE' ? L.cascade : reference[3] === 'SET NULL' ? L.setNull : L.restrict}`);
    if (check) rules.push(`${L.values}${check[2].replaceAll("'", '').split(/,\s*/).join(' / ')}`);
    if (between) rules.push(`${L.range} ${between[2]}–${between[3]}`);
    return { required: /NOT NULL|PRIMARY KEY/.test(def) ? L.yes : '', defaultValue: defaultValue ? defaultValue.replaceAll("'", '') : '', rules: rules.join(L.separator) };
  };
  const out = [L.begin, '', L.title, '', L.intro, ''];
  for (const section of sections) {
    out.push(`### ${section.number}. ${t(section.title)}`, '');
    for (const table of section.tables) {
      out.push(`#### \`${table.name}\`${table.view ? L.view : ''}`, '');
      if (table.comment) out.push(t(table.comment), '');
      if (table.view) {
        out.push(L.viewHeader, '|---|---|');
        for (const column of table.columns) out.push(`| \`${column.name}\` | ${escape(t(column.comment))} |`);
        out.push('');
        continue;
      }
      out.push(L.header, '|---|---|---|---|---|---|---|---|');
      for (const column of table.columns) {
        const info = describe(column);
        const note = notes[table.name]?.[column.name] ?? {};
        const meaningZh = [note.meaning, column.comment, LOCALES.zh.common[column.name]].filter(Boolean).sort((a, b) => b.length - a.length)[0] ?? '';
        const meaning = lang !== 'zh' && meaningZh === LOCALES.zh.common[column.name] ? L.common[column.name] : t(meaningZh);
        const source = note.source ? t(note.source) : L.commonSource[column.name];
        out.push(`| \`${column.name}\` | ${column.type} | ${info.required} | ${escape(info.defaultValue)} | ${escape(info.rules)} | ${escape(meaning)} | ${escape(t(note.sample))} | ${escape(source)} |`);
      }
      out.push('');
      if (table.constraints.length) out.push(`${L.constraints}${table.constraints.map((c) => `\`${c}\``).join(L.separator)}`, '');
      if (table.indexes.length) {
        out.push(table.indexes.map((x) => `${x.unique ? L.uniqueIndex : L.index} \`${x.name}\`${L.colon}(${x.columns})${x.where ? ` ${x.where}` : ''}`).join(L.separator), '');
      }
      if (table.translations.length) {
        out.push(`${L.translations(table.name)}${table.translations.map((x) => `\`${x.field}\` ${t(x.description)}${x.allowsJa ? L.includesJa : ''}`).join(L.listSeparator)}`, '');
      }
    }
  }
  out.push(END);
  return out.join('\n');
}

const sections = parse(sql);
const missing = new Set();
let stale = [];
for (const lang of Object.keys(LOCALES)) {
  const L = LOCALES[lang];
  const docUrl = new URL(L.doc, root);
  if (!existsSync(docUrl)) { stale.push(`${L.doc}（不存在）`); continue; }
  const generated = render(sections, lang, missing);
  const doc = readFileSync(docUrl, 'utf8');
  const start = doc.indexOf(L.begin);
  const end = doc.indexOf(END);
  const next = start >= 0 && end > start ? `${doc.slice(0, start)}${generated}${doc.slice(end + END.length)}` : `${doc.trimEnd()}\n\n${generated}\n`;
  if (next !== doc) {
    stale.push(L.doc);
    if (!process.argv.includes('--check') && !process.argv.includes('--missing')) writeFileSync(docUrl, next);
  }
}
if (process.argv.includes('--missing')) {
  console.log(JSON.stringify([...missing], null, 2));
} else if (process.argv.includes('--check')) {
  if (stale.length || missing.size) {
    if (stale.length) console.error(`与 server/v3/schema.sql 不一致：${stale.join('、')}。请运行 node scripts/v3/schema-doc.mjs`);
    if (missing.size) console.error(`缺少 ${missing.size} 条英文 / 日文翻译（server/v3/schema-doc.i18n.json），运行 --missing 查看`);
    process.exit(1);
  }
  console.log('三份文档与 SQL 一致，翻译齐全');
} else {
  const tables = sections.flatMap((s) => s.tables);
  console.log(`已生成：${tables.filter((x) => !x.view).length} 张表、${tables.filter((x) => x.view).length} 个视图、${tables.reduce((n, x) => n + x.columns.length, 0)} 列${missing.size ? `；缺少 ${missing.size} 条翻译` : ''}`);
}
